from __future__ import annotations

from dataclasses import asdict, dataclass
import os
from pathlib import Path


def load_project_env() -> None:
    """Load the local, gitignored .env without replacing real OS variables.

    The project deliberately avoids a dotenv dependency.  The supported format
    is the small KEY=value subset generated by ``cloud-configure``.  Keeping
    environment variables higher priority lets a CI job or an operator use a
    secret manager without changing this file.
    """
    env_path = Path(__file__).resolve().parents[1] / ".env"
    if not env_path.is_file():
        return
    for line in env_path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        key = key.strip()
        if not key or key in os.environ:
            continue
        value = value.strip()
        if len(value) >= 2 and value[0] == value[-1] and value[0] in {"'", '"'}:
            value = value[1:-1]
        os.environ[key] = value


load_project_env()


def optional_float_env(name: str) -> float | None:
    """Read an optional numeric deployment setting without inventing a value."""
    value = os.getenv(name, "").strip()
    return float(value) if value else None


@dataclass(frozen=True)
class Settings:
    sample_minutes: int = 5
    live_window: int = 288
    forecast_steps: int = 12
    et0_window_hours: int = 24
    short_gap_steps: int = 3
    observed_retrain_days: int = 14
    latitude_deg: float = 31.1979
    elevation_m: float = 3.0
    timezone: str = "Asia/Shanghai"
    soil_capacity_mm: float = 120.0
    initial_soil_fraction: float = 0.65
    crop_coefficient: float = 0.85
    proxy_irrigation_trigger_percent: float = 30.0
    proxy_irrigation_target_percent: float = 75.0
    database_path: Path = Path("runtime/forecast.sqlite3")
    artifact_dir: Path = Path("artifacts")
    llm_enabled: bool = os.getenv("AIOT_LLM_ENABLED", "0").lower() in {"1", "true", "yes", "on"}
    gateway_base_url: str = os.getenv("VEI_BASE_URL", "https://ai-gateway.vei.volces.com/v1")
    gateway_model: str = os.getenv("VEI_MODEL", "")
    gateway_timeout_seconds: float = float(os.getenv("VEI_TIMEOUT_SECONDS", "45"))
    actuator_mode: str = os.getenv("AIOT_ACTUATOR_MODE", "serial")
    max_watering_seconds: int = 60
    watering_cooldown_minutes: int = 15
    max_daily_watering_seconds: int = 600
    irrigation_trigger_percent: float = 30.0
    irrigation_target_percent: float = 75.0
    llm_min_interval_minutes: int = int(os.getenv("AIOT_LLM_INTERVAL_MINUTES", "15"))
    # Automatic irrigation is deliberately opt-in.  The cloud can recommend a
    # command, but the local computer remains the only component allowed to
    # queue it after fresh-data, forecast and policy checks.
    auto_irrigation_enabled: bool = os.getenv("AIOT_AUTO_IRRIGATION_ENABLED", "0").lower() in {"1", "true", "yes", "on"}
    auto_irrigation_min_confidence: float = float(os.getenv("AIOT_AUTO_IRRIGATION_MIN_CONFIDENCE", "0.80"))
    auto_irrigation_require_forecast_ready: bool = os.getenv(
        "AIOT_AUTO_IRRIGATION_REQUIRE_FORECAST_READY", "1"
    ).lower() in {"1", "true", "yes", "on"}
    # Retained only so older .env files remain parseable.  It no longer causes
    # actuation; use the explicit automatic-irrigation settings above.
    demo_auto_execute: bool = os.getenv("AIOT_DEMO_AUTO_EXECUTE", "0").lower() in {"1", "true", "yes", "on"}
    # Edge gateway event / sampling policy.  These values are deliberately
    # configured here rather than in the browser so a deployment can tune them
    # without changing the safety rules in firmware.
    event_cooldown_seconds: int = int(os.getenv("AIOT_EVENT_COOLDOWN_SECONDS", "300"))
    data_stale_seconds: int = int(os.getenv("AIOT_DATA_STALE_SECONDS", "20"))
    actuator_ack_timeout_seconds: int = int(os.getenv("AIOT_ACTUATOR_ACK_TIMEOUT_SECONDS", "15"))
    high_et_temp_c: float = float(os.getenv("AIOT_HIGH_ET_TEMP_C", "30"))
    high_et_solar_wm2: float = float(os.getenv("AIOT_HIGH_ET_SOLAR_WM2", "500"))
    high_et_wind_ms: float = float(os.getenv("AIOT_HIGH_ET_WIND_MS", "2"))
    high_et_soil_percent: float = float(os.getenv("AIOT_HIGH_ET_SOIL_PERCENT", "45"))
    night_solar_wm2: float = float(os.getenv("AIOT_NIGHT_SOLAR_WM2", "20"))
    night_wind_ms: float = float(os.getenv("AIOT_NIGHT_WIND_MS", "1"))
    valve_flow_lpm: float | None = (
        float(os.environ["AIOT_VALVE_FLOW_LPM"])
        if os.getenv("AIOT_VALVE_FLOW_LPM", "").strip() else None
    )
    # Farm facts are optional deployment metadata. They enrich cloud analysis
    # but are never part of the local safety policy or automatic actuation.
    farm_crop: str = os.getenv("AIOT_FARM_CROP", "").strip()
    farm_growth_stage: str = os.getenv("AIOT_FARM_GROWTH_STAGE", "").strip()
    farm_soil_type: str = os.getenv("AIOT_FARM_SOIL_TYPE", "").strip()
    farm_plot_area_m2: float | None = optional_float_env("AIOT_FARM_PLOT_AREA_M2")
    farm_irrigation_method: str = os.getenv("AIOT_FARM_IRRIGATION_METHOD", "").strip()
    farm_notes: str = os.getenv("AIOT_FARM_NOTES", "").strip()

    def to_dict(self) -> dict:
        data = asdict(self)
        data["database_path"] = str(self.database_path)
        data["artifact_dir"] = str(self.artifact_dir)
        return data

    def farm_profile(self) -> dict:
        """Return explicit farm facts for cloud analysis; never fill gaps by guesswork."""
        profile = {
            "crop": self.farm_crop or None,
            "growthStage": self.farm_growth_stage or None,
            "soilType": self.farm_soil_type or None,
            "plotAreaM2": self.farm_plot_area_m2,
            "irrigationMethod": self.farm_irrigation_method or None,
            "valveFlowLpm": self.valve_flow_lpm,
            "operatorNotes": self.farm_notes or None,
        }
        profile["status"] = "configured" if any(value is not None for value in profile.values()) else "not_configured"
        return profile


SETTINGS = Settings()
